/*
 * TIMER1_program.c
 *
 *  Created on: Nov 18, 2022
 *      Author: Mohamed Hashim Attiya Said
 */


// Libraries
#include "STD_TYPES.h"
#include "BIT_MATH.h"

// MCAL
#include "TIMER1_config.h"
#include "TIMER1_interface.h"
#include "TIMER1_private.h"
#include "TIMER1_register.h"





// Initialize Timer1
void TIMER1_voidInit(void)
{

#if TIMER1_OPERATION_MODE == TIMER_COUNTER_MODE

	/****************************** Wave Generation Mode Select ******************************/
#if TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_NORMAL__TOP_VAL_0XFFFF
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_8_BIT__TOP_VAL_0X00FF
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_9_BIT__TOP_VAL_0X01FF
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_10_BIT__TOP_VAL_0X03FF
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_CTC__TOP_VAL_OCR1A
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM_8_BIT__TOP_VAL_0X00FF
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM_9_BIT__TOP_VAL_0X01FF
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM_10_BIT__TOP_VAL_0X03FF
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	CLR_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT__TOP_VAL_ICR1
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT__TOP_VAL_OCR1A
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT__TOP_VAL_ICR1
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT__TOP_VAL_OCR1A
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	CLR_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_CTC__TOP_VAL_ICR1
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_RESERVED
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	CLR_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM__TOP_VAL_ICR1
	CLR_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#elif TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM__TOP_VAL_OCR1A
	SET_BIT(TCCR1A, TCCR1A_WGM10);
	SET_BIT(TCCR1A, TCCR1A_WGM11);
	SET_BIT(TCCR1B, TCCR1B_WGM12);
	SET_BIT(TCCR1B, TCCR1B_WGM13);

#else
#error "Wrong Wave Form Generation Mode"

#endif



	/****************************** Compare Match Output OC1A PinD5 Mode ******************************/

	//===================================================
	// Compare Match Output Mode: Non-PWM (Normal or CTC)
	//===================================================
#if (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_NORMAL__TOP_VAL_0XFFFF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_CTC__TOP_VAL_OCR1A) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_CTC__TOP_VAL_ICR1)

#if TIMER1_COMPARE_OUTPUT_MODE_NON_PWM_MODE_OC1A_PIND5 == TIMER1_NORMAL_PORT_OPERATION_OC1A_PIND5_DISCONNECTED
	CLR_BIT(TCCR1A, TCCR1A_COM1A0);
	CLR_BIT(TCCR1A, TCCR1A_COM1A1);

#elif TIMER1_COMPARE_OUTPUT_MODE_NON_PWM_MODE_OC1A_PIND5 == TIMER1_TOGGLE_OC1A_PIND5_ON_COMPARE_MATCH
	SET_BIT(TCCR1A, TCCR1A_COM1A0);
	CLR_BIT(TCCR1A, TCCR1A_COM1A1);

#elif TIMER1_COMPARE_OUTPUT_MODE_NON_PWM_MODE_OC1A_PIND5 == TIMER1_CLEAR_OC1A_PIND5_ON_COMPARE_MATCH__SET_OUTPUT_TO_LOW_LEVEL
	CLR_BIT(TCCR1A, TCCR1A_COM1A0);
	SET_BIT(TCCR1A, TCCR1A_COM1A1);

#elif TIMER1_COMPARE_OUTPUT_MODE_NON_PWM_MODE_OC1A_PIND5 == TIMER1_SET_OC1A_PIND5_ON_COMPARE_MATCH__SET_OUTPUT_TO_HIGH_LEVEL
	SET_BIT(TCCR1A, TCCR1A_COM1A0);
	SET_BIT(TCCR1A, TCCR1A_COM1A1);

#else
#error "Wrong Wave Compare Output Mode"
#endif

#endif


	//===================================================
	// Compare Match Output Mode: Fast PWM
	//===================================================
#if (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM_8_BIT__TOP_VAL_0X00FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM_9_BIT__TOP_VAL_0X01FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM_10_BIT__TOP_VAL_0X03FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM__TOP_VAL_ICR1) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM__TOP_VAL_OCR1A)

#if TIMER1_COMPARE_OUTPUT_MODE_FAST_PWM_MODE_OC1A_PIND5 == TIMER1_NORMAL_PORT_OPERATION_OC1A_PIND5_DISCONNECTED
	CLR_BIT(TCCR1A, TCCR1A_COM1A0);
	CLR_BIT(TCCR1A, TCCR1A_COM1A1);

#elif TIMER1_COMPARE_OUTPUT_MODE_FAST_PWM_MODE_OC1A_PIND5 == TIMER1_ACTION_ON_OC1A_PIND5_AND_OC1B_PIND4__DEPEND_ON_WAVE_GENERATION_MODE_SELECTION
	SET_BIT(TCCR1A, TCCR1A_COM1A0);
	CLR_BIT(TCCR1A, TCCR1A_COM1A1);

#elif TIMER1_COMPARE_OUTPUT_MODE_FAST_PWM_MODE_OC1A_PIND5 == TIMER1_CLEAR_OC1A_PIND5_ON_COMPARE_MATCH_SET_OC1A_PIND5_AT_TOP
	CLR_BIT(TCCR1A, TCCR1A_COM1A0);
	SET_BIT(TCCR1A, TCCR1A_COM1A1);

#elif TIMER1_COMPARE_OUTPUT_MODE_FAST_PWM_MODE_OC1A_PIND5 == TIMER1_SET_OC1A_PIND5_ON_COMPARE_MATCH_CLEAR_OC1A_PIND5_AT_TOP
	SET_BIT(TCCR1A, TCCR1A_COM1A0);
	SET_BIT(TCCR1A, TCCR1A_COM1A1);

#else
#error "Wrong Wave Compare Output Mode"
#endif

#endif



	//===================================================
	// Compare Match Output Mode: PWM Phase Correct
	//===================================================
#if (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_8_BIT__TOP_VAL_0X00FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_9_BIT__TOP_VAL_0X01FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_10_BIT__TOP_VAL_0X03FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT__TOP_VAL_ICR1) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT__TOP_VAL_OCR1A) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT__TOP_VAL_ICR1) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT__TOP_VAL_OCR1A)

#if TIMER1_COMPARE_OUTPUT_MODE_PHASE_CORRECT_PWM_MODE_OC1A_PIND5 == TIMER1_NORMAL_PORT_OPERATION_OC1A_PIND5_DISCONNECTED
	CLR_BIT(TCCR1A, TCCR1A_COM1A0);
	CLR_BIT(TCCR1A, TCCR1A_COM1A1);

#elif TIMER1_COMPARE_OUTPUT_MODE_PHASE_CORRECT_PWM_MODE_OC1A_PIND5 == TIMER1_ACTION_ON_OC1A_PIND5_AND_OC1B_PIND4__DEPEND_ON_WAVE_GENERATION_MODE_SELECTION
	SET_BIT(TCCR1A, TCCR1A_COM1A0);
	CLR_BIT(TCCR1A, TCCR1A_COM1A1);

#elif TIMER1_COMPARE_OUTPUT_MODE_PHASE_CORRECT_PWM_MODE_OC1A_PIND5 == TIMER1_CLEAR_OC1A_PIND5_ON_COMPARE_MATCH_WHEN_UP_COUNTING_SET_OC1A_PIND5_ON_COMPARE_MATCH_WHEN_DOWNCOUNTING
	CLR_BIT(TCCR1A, TCCR1A_COM1A0);
	SET_BIT(TCCR1A, TCCR1A_COM1A1);

#elif TIMER1_COMPARE_OUTPUT_MODE_PHASE_CORRECT_PWM_MODE_OC1A_PIND5 == TIMER1_SET_OC1A_PIND5_ON_COMPARE_MATCH_WHEN_UP_COUNTING_CLEAR_OC1A_PIND5_ON_COMPARE_MATCH_WHEN_DOWNCOUNTING
	SET_BIT(TCCR1A, TCCR1A_COM1A0);
	SET_BIT(TCCR1A, TCCR1A_COM1A1);

#else
#error "Wrong Wave Compare Output Mode"
#endif

#endif



	/****************************** Compare Match Output OC1B PinD4 Mode ******************************/

	//===================================================
	// Compare Match Output Mode: Non-PWM (Normal or CTC)
	//===================================================
#if (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_NORMAL__TOP_VAL_0XFFFF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_CTC__TOP_VAL_OCR1A) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_CTC__TOP_VAL_ICR1)

#if TIMER1_COMPARE_OUTPUT_MODE_NON_PWM_MODE_OC1B_PIND4 == TIMER1_NORMAL_PORT_OPERATION_OC1B_PIND4_DISCONNECTED
	CLR_BIT(TCCR1A, TCCR1A_COM1B0);
	CLR_BIT(TCCR1A, TCCR1A_COM1B1);

#elif TIMER1_COMPARE_OUTPUT_MODE_NON_PWM_MODE_OC1B_PIND4 == TIMER1_TOGGLE_OC1B_PIND4_ON_COMPARE_MATCH
	SET_BIT(TCCR1A, TCCR1A_COM1B0);
	CLR_BIT(TCCR1A, TCCR1A_COM1B1);

#elif TIMER1_COMPARE_OUTPUT_MODE_NON_PWM_MODE_OC1B_PIND4 == TIMER1_CLEAR_OC1B_PIND4_ON_COMPARE_MATCH__SET_OUTPUT_TO_LOW_LEVEL
	CLR_BIT(TCCR1A, TCCR1A_COM1B0);
	SET_BIT(TCCR1A, TCCR1A_COM1B1);

#elif TIMER1_COMPARE_OUTPUT_MODE_NON_PWM_MODE_OC1B_PIND4 == TIMER1_SET_OC1B_PIND4_ON_COMPARE_MATCH__SET_OUTPUT_TO_HIGH_LEVEL
	SET_BIT(TCCR1A, TCCR1A_COM1B0);
	SET_BIT(TCCR1A, TCCR1A_COM1B1);

#else
#error "Wrong Wave Compare Output Mode"
#endif

#endif


	//===================================================
	// Compare Match Output Mode: Fast PWM
	//===================================================
#if (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM_8_BIT__TOP_VAL_0X00FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM_9_BIT__TOP_VAL_0X01FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM_10_BIT__TOP_VAL_0X03FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM__TOP_VAL_ICR1) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_FAST_PWM__TOP_VAL_OCR1A)

#if TIMER1_COMPARE_OUTPUT_MODE_FAST_PWM_MODE_OC1B_PIND4 == TIMER1_NORMAL_PORT_OPERATION_OC1B_PIND4_DISCONNECTED
	CLR_BIT(TCCR1A, TCCR1A_COM1B0);
	CLR_BIT(TCCR1A, TCCR1A_COM1B1);

#elif TIMER1_COMPARE_OUTPUT_MODE_FAST_PWM_MODE_OC1B_PIND4 == TIMER1_ACTION1B_ON_OC1A_PIND5_AND_OC1B_PIND4__DEPEND_ON_WAVE_GENERATION_MODE_SELECTION
	SET_BIT(TCCR1A, TCCR1A_COM1B0);
	CLR_BIT(TCCR1A, TCCR1A_COM1B1);

#elif TIMER1_COMPARE_OUTPUT_MODE_FAST_PWM_MODE_OC1B_PIND4 == TIMER1_CLEAR_OC1B_PIND4_ON_COMPARE_MATCH_SET_OC1B_PIND4_AT_TOP
	CLR_BIT(TCCR1A, TCCR1A_COM1B0);
	SET_BIT(TCCR1A, TCCR1A_COM1B1);

#elif TIMER1_COMPARE_OUTPUT_MODE_FAST_PWM_MODE_OC1B_PIND4 == TIMER1_SET_OC1B_PIND4_ON_COMPARE_MATCH_CLEAR_OC1B_PIND4_AT_TOP
	SET_BIT(TCCR1A, TCCR1A_COM1B0);
	SET_BIT(TCCR1A, TCCR1A_COM1B1);

#else
#error "Wrong Wave Compare Output Mode"
#endif

#endif



	//===================================================
	// Compare Match Output Mode: PWM Phase Correct
	//===================================================
#if (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_8_BIT__TOP_VAL_0X00FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_9_BIT__TOP_VAL_0X01FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT_10_BIT__TOP_VAL_0X03FF) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT__TOP_VAL_ICR1) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_AND_FREQUENCY_CORRECT__TOP_VAL_OCR1A) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT__TOP_VAL_ICR1) || (TIMER1_WAVE_FORM_GENERATION_MODE == TIMER1_PWM_PHASE_CORRECT__TOP_VAL_OCR1A)

#if TIMER1_COMPARE_OUTPUT_MODE_PHASE_CORRECT_PWM_MODE_OC1B_PIND4 == TIMER1_NORMAL_PORT_OPERATION_OC1B_PIND4_DISCONNECTED
	CLR_BIT(TCCR1A, TCCR1A_COM1B0);
	CLR_BIT(TCCR1A, TCCR1A_COM1B1);

#elif TIMER1_COMPARE_OUTPUT_MODE_PHASE_CORRECT_PWM_MODE_OC1B_PIND4 == TIMER1_ACTION2B_ON_OC1A_PIND5_AND_OC1B_PIND4__DEPEND_ON_WAVE_GENERATION_MODE_SELECTION
	SET_BIT(TCCR1A, TCCR1A_COM1B0);
	CLR_BIT(TCCR1A, TCCR1A_COM1B1);

#elif TIMER1_COMPARE_OUTPUT_MODE_PHASE_CORRECT_PWM_MODE_OC1B_PIND4 == TIMER1_CLEAR_OC1B_PIND4_ON_COMPARE_MATCH_WHEN_UP_COUNTING_SET_OC1B_PIND4_ON_COMPARE_MATCH_WHEN_DOWNCOUNTING
	CLR_BIT(TCCR1A, TCCR1A_COM1B0);
	SET_BIT(TCCR1A, TCCR1A_COM1B1);

#elif TIMER1_COMPARE_OUTPUT_MODE_PHASE_CORRECT_PWM_MODE_OC1B_PIND4 == TIMER1_SET_OC1B_PIND4_ON_COMPARE_MATCH_WHEN_UP_COUNTING_CLEAR_OC1B_PIND4_ON_COMPARE_MATCH_WHEN_DOWNCOUNTING
	SET_BIT(TCCR1A, TCCR1A_COM1B0);
	SET_BIT(TCCR1A, TCCR1A_COM1B1);

#else
#error "Wrong Wave Compare Output Mode"
#endif

#endif


#endif


	/******************************** Pre-scaler Clock Select ********************************/
#if TIMER1_PRE_SCALER_SELECT == TIMER1_NO_CLOCK_SOURCE
	CLR_BIT(TCCR1B, TCCR1B_CS10);
	CLR_BIT(TCCR1B, TCCR1B_CS11);
	CLR_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_PRE_SCALER_SELECT == TIMER1_NO_PRE_SCALING
	SET_BIT(TCCR1B, TCCR1B_CS10);
	CLR_BIT(TCCR1B, TCCR1B_CS11);
	CLR_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_PRE_SCALER_SELECT == TIMER1_PRE_SCALER_8
	CLR_BIT(TCCR1B, TCCR1B_CS10);
	SET_BIT(TCCR1B, TCCR1B_CS11);
	CLR_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_PRE_SCALER_SELECT == TIMER1_PRE_SCALER_64
	SET_BIT(TCCR1B, TCCR1B_CS10);
	SET_BIT(TCCR1B, TCCR1B_CS11);
	CLR_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_PRE_SCALER_SELECT == TIMER1_PRE_SCALER_256
	CLR_BIT(TCCR1B, TCCR1B_CS10);
	CLR_BIT(TCCR1B, TCCR1B_CS11);
	SET_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_PRE_SCALER_SELECT == TIMER1_PRE_SCALER_1024
	SET_BIT(TCCR1B, TCCR1B_CS10);
	CLR_BIT(TCCR1B, TCCR1B_CS11);
	SET_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_PRE_SCALER_SELECT == TIMER1_EXTERNAL_CLOCK_SOURCE_ON_T0_PIN_ON_FALLING_EDGE
	CLR_BIT(TCCR1B, TCCR1B_CS10);
	SET_BIT(TCCR1B, TCCR1B_CS11);
	SET_BIT(TCCR1B, TCCR1B_CS12);

#elif TIMER1_PRE_SCALER_SELECT == TIMER1_EXTERNAL_CLOCK_SOURCE_ON_T0_PIN_ON_RISING_EDGE
	SET_BIT(TCCR1B, TCCR1B_CS10);
	SET_BIT(TCCR1B, TCCR1B_CS11);
	SET_BIT(TCCR1B, TCCR1B_CS12);

#else
#error	"Wrong Pre-scaler Select"
#endif
}





#if TIMER1_OPERATION_MODE == TIMER_COUNTER_MODE

/****************************** Fast PWM Mode functions ******************************/
// Set the top value (overflow value) in ICR1 register that maps to the required periodic time in Fast PWM mode
void TIMER1_voidSetTopVal(u16 copy_u16TopVal)
{
	ICR1 = copy_u16TopVal;
}

// Set the compare match value in OCR1A register that maps to the ON Time in Fast PWM Mode
void TIMER1_voidCompareMatchVal(u16 copy_u16CompVal)
{
	OCR1A = copy_u16CompVal;
}

#endif





/**********************************************************************************************************************************************************/



#if TIMER1_OPERATION_MODE == ICU_MODE

/*************************************** ICU Part ***************************************/
// Global Pointer to function to be used in callback
void (*TIMER1_pvGlobCallBackFunc)(void) = NULL;


// ICU Initialization
void ICU_voidInit(void)
{
	// Enable ICU noise canceler
	SET_BIT(TCCR1B, TCCR1B_ICNC1);

	// Choose the trigger edge as rising edge
	SET_BIT(TCCR1B, TCCR1B_ICES1);

	// Enable "Input Capture Interrupt Enable"
	SET_BIT(TIMSK, TIMSK_TICIE1);
}

// Select Edge, rising or falling edge
u8 ICU_u8EdgeSelect(u8 copy_u8Edge)
{
	u8 local_u8ErrorCodeStatus = OK;
	switch(copy_u8Edge)
	{
	case ICU_RISING_EDGE	: SET_BIT(TCCR1B, TCCR1B_ICES1); break;
	case ICU_FALLING_EDGE	: CLR_BIT(TCCR1B, TCCR1B_ICES1); break;
	default					: local_u8ErrorCodeStatus = NOT_OK;
	}
	return local_u8ErrorCodeStatus;
}

// Reading the signal detected by ICU
u16 ICU_u16InputCaptureRead(void)
{
	return ICR1;
}

// Enable ICU
void ICU_voidInterruptEnable(void)
{
	// Enable "Input Capture Interrupt Enable"
	SET_BIT(TIMSK, TIMSK_TICIE1);
}

// Disable ICU
void ICU_voidInterruptDisable(void)
{
	// Disable "Input Capture Interrupt Enable"
	CLR_BIT(TIMSK, TIMSK_TICIE1);
}


// Callback function to Timer1 ISR
void TIMER1_voidSetCallBack(void (*copy_pvUserFunc)(void))
{
	if(copy_pvUserFunc != NULL)
	{
		TIMER1_pvGlobCallBackFunc = copy_pvUserFunc;
	}
}



void __vector_6(void) __attribute__((signal));
void __vector_6(void)
{
	if(TIMER1_pvGlobCallBackFunc != NULL)
	{
		TIMER1_pvGlobCallBackFunc();
	}
}

#endif

















